### ISSUE TITLE
Graphics driver error (?)

### ISSUE THREAD

**Issue by stxrm-cc** [Mic238/osu-for-Mac-Stable-Latest#23]
https://gyazo.com/e3d67b1d379742fe7758d5fff0223b5e

Error:
#=zEixiY7MdWSVkdbjqAgPhfzmyP7mG: No available GL context found. ---> OpenTK.Graphics.GraphicsContextException: Failed to initialize EGL, error BAD_ALLOC.
   at OpenTK.Platform.Egl.EglWindowInfo..ctor(IntPtr handle, IntPtr display, IntPtr surface)
   at OpenTK.Platform.Egl.EglAnglePlatformFactory.CreateWindowInfo(IAngleWindowInfoInternal window_info, Int32 major, GraphicsContextFlags flags)
   at OpenTK.Platform.Egl.EglAnglePlatformFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at #=zWPE$u4ORwrPXVd5c$ADmyhQpt8OY.#=zSR_05Vk=(Int32 #=zUF2H8EQ=, Int32 #=zIYSPofw=, GraphicsContextFlags #=zy4PYHXE=)
   at #=zmoqGK36N$yW3xpWv073wHic=.#=zRldxUN4cvXyM(GraphicsContextFlags #=zy4PYHXE=)
   --- End of inner exception stack trace ---
   at #=zmoqGK36N$yW3xpWv073wHic=.#=zRldxUN4cvXyM(GraphicsContextFlags #=zy4PYHXE=)
   at #=zmoqGK36N

**Comment by Mic238** [comment]
please include more details eg hardware and os version. Copy and paste the log wouldn't help to diagnostic
